package com.wm.request;
import java.util.List;

import com.wm.model.plats;

import lombok.Data;

@Data
public class CreateMenuRequest {
    private List<plats> items;
    private String nom_restaurant;
    private double total;

    // Constructors, getters, and setters can be generated by Lombok
}